Added bootstrap Css and refactor
trippykyle/todo pull request #1
Opened 2024-03-19 00:20 UTC by trippykyle

2024-03-21 01:45 UTC, francoisa commented
the form partial is not styled using bootstrap.

2024-03-21 01:46 UTC, francoisa requested changes
See my comments.

2024-03-21 01:46 UTC, francoisa commented on Gemfile
Remove jbuilder from the file with 'bundle remove'

2024-03-21 01:46 UTC, francoisa commented on Gemfile
> +gem "bootstrap", "~> 5.3"
Move these above the `group` blocks.

2024-03-21 01:46 UTC, francoisa commented on app/views/tasks/edit.html.erb
> +Editing
indentation is off or put on one line

2024-03-21 01:46 UTC, francoisa commented on app/views/tasks/edit.html.erb
> +<%= link_to "Tasks", tasks_path, {class: 'btn btn-success btn-sm'} %>
indentation

2024-03-21 01:46 UTC, francoisa commented on app/views/tasks/index.html.erb
> +          <strong>Content:</strong>
not needed.

2024-03-22 07:18 UTC, trippykyle commented
> the form partial is not styled using bootstrap.

not sure where to find the partial form

2024-03-24 22:17 UTC, francoisa commented
> > the form partial is not styled using bootstrap.
> 
> not sure where to find the partial form
the [partial](https://guides.rubyonrails.org/layouts_and_rendering.html#using-partials) I was referring to is:  **app/views/tasks/_form.html.erb**

2024-03-25 05:36 UTC, francoisa requested changes

2024-03-25 05:36 UTC, francoisa commented on app/views/tasks/edit.html.erb
> +    <%= render "form", task: @task %>
```suggestion
<%= render "form", task: @task %>
```

2024-03-25 05:36 UTC, francoisa commented on app/views/tasks/edit.html.erb
> +    <br>
```suggestion
<br>
```

2024-03-25 23:08 UTC, francoisa approved these changes
Looks good to me

2024-03-25 23:10 UTC, merged